---
title: "ShinyBandit"
bibliography: homepage.bib
---

ShinyBandit is an implimentation of a Bandit task. Bandit tasks are prototypical examples of *reinforcement learning* tasks where an person (or animal or organization) is trying to maximize their rewards by interacting with an uncertain environment [@sutton1998reinforcement].

```{r, echo = FALSE, fig.width = 6, fig.height = 4, fig.align='center', eval = FALSE}

options.n <- 3

  #   Boxes
  box.center.x <- seq(.1, .9, length.out = options.n)
  box.center.y <- rep(.5, options.n)
  box.height <- .75
  box.width <- 1 / (options.n + 1)
  
  box.x0.v <- box.center.x - box.width / 2
  box.y0.v <- box.center.y - box.height / 2
  box.x1.v <- box.center.x + box.width / 2
  box.y1.v <- box.center.y + box.height / 2
  
  #   Tickets
  ticket.n <- 8
  ticket.width <- box.width / 15
  ticket.height <- box.height / 15
  ticket.col <- gray(.9)
  
  ticket.x.v <- as.numeric(sapply(1:options.n, FUN = function(x) {
    
    rep(seq(from = box.center.x[x] - box.width / 3,
            to = box.center.x[x] + box.width / 3,
            length.out = ticket.n), each = ticket.n)
    
  }))
  
  ticket.y.v <- as.numeric(sapply(1:options.n, FUN = function(x) {
    
    rep(seq(from = box.center.y[x] - box.height / 3,
            to = box.center.y[x] + box.height / 3,
            length.out = ticket.n), times = ticket.n)
    
  }))
  
  ticket.x0.v <- ticket.x.v - ticket.width / 2
  ticket.x1.v <- ticket.x.v + ticket.width / 2
  ticket.y0.v <- ticket.y.v - ticket.height / 2
  ticket.y1.v <- ticket.y.v + ticket.height / 2
  
  # Section E2: Main game display
  
  bandit.display <- function(outcome,                # What is the outcome on this trial?
                             selection,              # Which option is selected?
                             points,                 # How many points have been earned?
                             trials.left,            # How many trials remain?
                             pos.col = "green3",     # Color of positive outcomes
                             neg.col = "indianred1", # Color of negative outcomes
                             neu.col = "gray") {     # Color of neutral outcomes
    
    # Determine current outcome and display
    if(is.numeric(outcome)) {
      
      if(outcome > 0) {
        text.col <- pos.col
        current.outcome.disp <- paste0("+", outcome)
      }
      
      if(outcome < 0) {
        text.col <- neg.col
        current.outcome.disp <- outcome
      }
      
      if(outcome == 0) {
        text.col <- neu.col
        current.outcome.disp <- outcome
      }
    }
    
    if(is.numeric(outcome) == FALSE) {
      
      text.col <- "black"
      current.outcome.disp <- outcome
      
    }
    
    # Plotting space
    par(mar = c(1, 1, 1, 1))
    layout(matrix(c(1, 2), nrow = 2, ncol = 1, byrow = TRUE), heights = c(3, 3), widths = c(9))
    
    # Title row
    plot.new()
    text(c(.5, .85), c(.7, .7), labels = c("Points Earned", "Draws Remaining"), cex = 1, font = 3)
    text(c(.5, .85), c(.4, .4), labels = c(points, trials.left), cex = 2)
    abline(h = .2, col = gray(.5), lwd = 2)
    
    # Option display
    
    plot(1, xlim = c(0, 1), ylim = c(0, 1), type = "n", 
         xaxt = "n", yaxt = "n", bty = "n", xlab = "", ylab = "")
    
    # Options
    rect(xleft = box.x0.v, ybottom = box.y0.v,
         xright = box.x1.v, ytop = box.y1.v, 
         lwd = 2)
    
    # Tickets
    rect(xleft = ticket.x0.v,
         ybottom = ticket.y0.v,
         xright = ticket.x1.v,
         ytop = ticket.y1.v,
         col = ticket.col, lwd = .5, 
         border = gray(.3))
    
    # Option Labels
    mtext(LETTERS[1:options.n], side = 3, cex = 2, at = box.center.x)
    
    # Outcome display
    if(is.finite(selection)) {
      
      # Outcome border
      rect(xleft = box.center.x[selection] - box.width * .4,
           ybottom = box.center.y[selection] - box.height * .4,
           xright = box.center.x[selection] + box.width * .4,
           ytop = box.center.y[selection] + box.height * .4,
           col = "white"
      )
      # Outcome Display
      text(x = box.center.x[selection], y = .5, 
           current.outcome.disp, cex = 7, col = text.col)
      
    }
    
  }
  
  bandit.display(0, NA, 0, 50)
  
```

In the task, players are presented with options (in this case, 3) represented as boxes. The boxes contain many tickets. Each ticket has a point value written on it ranging from -100 to +100. Tickets with high positive values are valuable and result in points, while tickets with low negative values are to be avoided as they remove points.

Each box has its own distribution of tickets. However, players do not know for sure what the distribution of ticket values is in each box. Some boxes may have higher ticket values on average than others, and some may have more variable ticket values than others.

Players have a fixed (e.g.; 50) number of trials where they can select a box and draw a random ticket. When a ticket is drawn, the point value on the ticket is displayed and its value is added (or subtracted) to the player's cumulative point total. The ticket is then returned to the box. When the final trial is completed, the game is over.

Players play the game several times. The distributions (boxes) are the same in each game. However, their location is randomly determined at the start of each game. Therefore, while players can learn about the overall decision environment from one game to another, they will always have to learn which option is which in each game.

## Play ShinyBandit

You can play ShinyBandit at [https://econpsychbasel.shinyapps.io/ShinyBandit/](https://econpsychbasel.shinyapps.io/ShinyBandit/) or in the window below (Note that the app runs smoother in a separate window):

<iframe src="https://econpsychbasel.shinyapps.io/ShinyBandit/", height = 500px, width = 900px, align = middle></iframe>


## Source code

See [http://www.github.com/ndphillips/ShinyBandit](http://www.github.com/ndphillips/ShinyBandit) for additional details of the code


# References